In [11]:
import numpy as np
import pandas as pd
import pygad

In [12]:
file = pd.read_csv('11.txt', delimiter = ' ')
file

      13000   12
205     0.8  173
489     0.4  172
1230    1.0  344
859     0.6  173
1015    0.9  333
1524    1.0  250
1643    0.6  338
1541    0.7  324
1010    0.5  359
1465    1.2  199
1571    1.0  350
1092    0.9  277
470     1.0  301
959     0.9  137
876     0.6  140
669     0.9  304
1036    0.4  204
412     0.9  130
945     1.0  315
611     0.6  389
825     0.7  354
1487    0.9  102
984     0.9  274
1576    0.4  150
797     0.4  256
1555    1.0  343
786     1.1  375
1502    0.5  173
830     0.6  369
399     1.1  195

In [13]:
params = file.columns.tolist()
W = int(params[0])
V = int(params[1])
file.columns = ['v', 'c']
file['w'] = file.index
data = file[['w','v','c']].values.tolist()
data

[[205.0, 0.8, 173.0],
 [489.0, 0.4, 172.0],
 [1230.0, 1.0, 344.0],
 [859.0, 0.6, 173.0],
 [1015.0, 0.9, 333.0],
 [1524.0, 1.0, 250.0],
 [1643.0, 0.6, 338.0],
 [1541.0, 0.7, 324.0],
 [1010.0, 0.5, 359.0],
 [1465.0, 1.2, 199.0],
 [1571.0, 1.0, 350.0],
 [1092.0, 0.9, 277.0],
 [470.0, 1.0, 301.0],
 [959.0, 0.9, 137.0],
 [876.0, 0.6, 140.0],
 [669.0, 0.9, 304.0],
 [1036.0, 0.4, 204.0],
 [412.0, 0.9, 130.0],
 [945.0, 1.0, 315.0],
 [611.0, 0.6, 389.0],
 [825.0, 0.7, 354.0],
 [1487.0, 0.9, 102.0],
 [984.0, 0.9, 274.0],
 [1576.0, 0.4, 150.0],
 [797.0, 0.4, 256.0],
 [1555.0, 1.0, 343.0],
 [786.0, 1.1, 375.0],
 [1502.0, 0.5, 173.0],
 [830.0, 0.6, 369.0],
 [399.0, 1.1, 195.0]]

In [14]:
def fitness(solution, solution_index):
    w = 0 
    v = 0
    c = 0 
    for (array, item) in zip(solution, data):
        if array > 0:
            w += item[0]
            v += item[1]
            c += item[2]
    if w > W or v > V:
        c = 0
    return c

In [15]:
ga_instance = pygad.GA(num_generations=250, #Количество поколений
                       num_parents_mating=2, #Количество решений, которые будут выбраны в качестве родителей
                       fitness_func=fitness, #Функция, вычисляющая значение пригодности решения
                       sol_per_pop=35, #Количество решений в популяции
                       num_genes=len(data), #Количество генов в решении
                       init_range_low=-1, #Нижнее значение случайного диапазона, из которого выбираются значения генов в исходной популяции
                       init_range_high=1 #Верхнее значение случайного диапазона, из которого выбираются значения генов в исходной популяции
                       )

In [17]:
ga_instance.run()
solution, solution_fitness, solution_idx = ga_instance.best_solution()

In [19]:
result = []
for i in range(0, len(data)):
    if solution[i] > 0:
        result.append(data[i])
result_file = pd.DataFrame.from_records(result, columns=['w','v','c'])

In [20]:
print(solution_fitness)
print(result_file)
w = 0
v = 0
c = 0
for i in range(0, len(result_file)):
        w += result_file.at[i,'w']
        v += result_file.at[i,'v']
        c += result_file.at[i,'c']
print("Вес:", w, "(Грузоподъемноcть:", W, ")")
print("Объем:", round(v,1), "(Вместимость:", V, ")")
print("Ценность:", c)

4471.0
         w    v      c
0    205.0  0.8  173.0
1    489.0  0.4  172.0
2   1230.0  1.0  344.0
3   1010.0  0.5  359.0
4    470.0  1.0  301.0
5    669.0  0.9  304.0
6   1036.0  0.4  204.0
7    945.0  1.0  315.0
8    611.0  0.6  389.0
9    825.0  0.7  354.0
10   984.0  0.9  274.0
11  1555.0  1.0  343.0
12   786.0  1.1  375.0
13   830.0  0.6  369.0
14   399.0  1.1  195.0
Вес: 12044.0 (Грузоподъемноcть: 13000 )
Объем: 12.0 (Вместимость: 12 )
Ценность: 4471.0

In [23]:
file=open('4.1.txt','w', encoding='utf-8')
file.write(result_file.to_string())
file.write("\nВес: " + str(w) + " (Грузоподъемноcть: " + str(W) + ")")
file.write("\nОбъем: " + str(round(v,1)) + " (Вместимость: " + str(V) + ")")
file.write("\nЦенность: " + str(c))
file.close()